name: polifenois_web
description: "Sistemas Web para o Projeto Polifenóis - Vetix Tecnologia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Versão mais flexível para garantir compatibilidade no Render

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.19.0
  file_picker: ^8.0.0      # Necessário para o Dashboard da Gestante
  image_picker: ^1.1.2     # Necessário para o Dashboard Master (Câmera)
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mosaico.jpg